//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uni_Books.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("213, 223, 208")]
        public global::System.Drawing.Color LV1_A {
            get {
                return ((global::System.Drawing.Color)(this["LV1_A"]));
            }
            set {
                this["LV1_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 206, 244")]
        public global::System.Drawing.Color LV1_B {
            get {
                return ((global::System.Drawing.Color)(this["LV1_B"]));
            }
            set {
                this["LV1_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 235, 249")]
        public global::System.Drawing.Color LV2_A {
            get {
                return ((global::System.Drawing.Color)(this["LV2_A"]));
            }
            set {
                this["LV2_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 238, 225")]
        public global::System.Drawing.Color LV2_B {
            get {
                return ((global::System.Drawing.Color)(this["LV2_B"]));
            }
            set {
                this["LV2_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Data\\Accounts_Data.dat")]
        public string filename {
            get {
                return ((string)(this["filename"]));
            }
            set {
                this["filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pwd {
            get {
                return ((string)(this["pwd"]));
            }
            set {
                this["pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SRPI_B642_JM21_CWFA")]
        public string app_key {
            get {
                return ((string)(this["app_key"]));
            }
            set {
                this["app_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool auto_acct_ids {
            get {
                return ((bool)(this["auto_acct_ids"]));
            }
            set {
                this["auto_acct_ids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto_date {
            get {
                return ((bool)(this["auto_date"]));
            }
            set {
                this["auto_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Account")]
        public string Account_descr {
            get {
                return ((string)(this["Account_descr"]));
            }
            set {
                this["Account_descr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Count")]
        public string Count_descr {
            get {
                return ((string)(this["Count_descr"]));
            }
            set {
                this["Count_descr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Increase")]
        public string Increase_descr {
            get {
                return ((string)(this["Increase_descr"]));
            }
            set {
                this["Increase_descr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Decrease")]
        public string Decrease_descr {
            get {
                return ((string)(this["Decrease_descr"]));
            }
            set {
                this["Decrease_descr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nothing")]
        public string Nothing_descr {
            get {
                return ((string)(this["Nothing_descr"]));
            }
            set {
                this["Nothing_descr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Whole_Numbers {
            get {
                return ((bool)(this["Whole_Numbers"]));
            }
            set {
                this["Whole_Numbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Keep_Time {
            get {
                return ((bool)(this["Keep_Time"]));
            }
            set {
                this["Keep_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Acct_Show_Balance {
            get {
                return ((bool)(this["Acct_Show_Balance"]));
            }
            set {
                this["Acct_Show_Balance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Acct_Show_Average {
            get {
                return ((bool)(this["Acct_Show_Average"]));
            }
            set {
                this["Acct_Show_Average"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Count")]
        public string Default_activity {
            get {
                return ((string)(this["Default_activity"]));
            }
            set {
                this["Default_activity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal Default_amount {
            get {
                return ((decimal)(this["Default_amount"]));
            }
            set {
                this["Default_amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$#,###,##0.00")]
        public string Amount_format {
            get {
                return ((string)(this["Amount_format"]));
            }
            set {
                this["Amount_format"] = value;
            }
        }
    }
}
